//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.Bill_Detail = new HashSet<Bill_Detail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Customer { get; set; }
        public Nullable<System.DateTime> Date_order { get; set; }
        public string Address { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string Phone_Number { get; set; }
    
        public virtual ICollection<Bill_Detail> Bill_Detail { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
