//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colorr
    {
        public Colorr()
        {
            this.Product_Color = new HashSet<Product_Color>();
        }
    
        public int ID { get; set; }
        public string Color { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<Product_Color> Product_Color { get; set; }
    }
}
