<?xml version="1.0" encoding="utf-8"?><Database Name="LaptopTK" Class="laptopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=THEKY\SQLEXPRESS;Initial Catalog=LaptopTK;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LaptopTKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Slide" Member="Slides">
    <Type Name="Slide">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Action" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Discount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Bills" Member="Bills">
    <Type Name="Bill">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date_order" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="[Confirm]" Member="Confirm" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Bill_Bill_Detail" Member="Bill_Details" ThisKey="ID" OtherKey="ID_Bill" Type="Bill_Detail" />
      <Association Name="Customer_Bill" Member="Customer" ThisKey="ID_Customer" OtherKey="ID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Brand" Member="Brands">
    <Type Name="Brand">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Brand_Product" Member="Products" ThisKey="ID" OtherKey="ID_Brand" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Product_Color" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity_Purchased" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_Color_Cart" Member="Product_Color" ThisKey="ID_Product_Color" OtherKey="ID" Type="Product_Color" IsForeignKey="true" />
      <Association Name="Customer_Cart" Member="Customer" ThisKey="ID_Customer" OtherKey="ID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Colorr" Member="Colorrs">
    <Type Name="Colorr">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Colorr_Product_Color" Member="Product_Colors" ThisKey="ID" OtherKey="ID_Color" Type="Product_Color" />
    </Type>
  </Table>
  <Table Name="dbo.Favorites_list" Member="Favorites_lists">
    <Type Name="Favorites_list">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Customer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_Favorites_list" Member="Product" ThisKey="ID_Product" OtherKey="ID" Type="Product" IsForeignKey="true" />
      <Association Name="Customer_Favorites_list" Member="Customer" ThisKey="ID_Customer" OtherKey="ID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.New_Image" Member="New_Images">
    <Type Name="New_Image">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_New" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="New_New_Image" Member="New" ThisKey="ID_New" OtherKey="ID" Type="New" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.News" Member="News">
    <Type Name="New">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="New_New_Image" Member="New_Images" ThisKey="ID" OtherKey="ID_New" Type="New_Image" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_Brand" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Group_Pro" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Promotion_Price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CPU" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="GPU" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="RAM" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="ROM" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Monitor" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="Operating" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Warranty" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Pin" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Weight" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Product_Favorites_list" Member="Favorites_lists" ThisKey="ID" OtherKey="ID_Product" Type="Favorites_list" />
      <Association Name="Product_Product_Color" Member="Product_Colors" ThisKey="ID" OtherKey="ID_Product" Type="Product_Color" />
      <Association Name="Product_Product_Image" Member="Product_Images" ThisKey="ID" OtherKey="ID_Product" Type="Product_Image" />
      <Association Name="Brand_Product" Member="Brand" ThisKey="ID_Brand" OtherKey="ID" Type="Brand" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Color" Member="Product_Colors">
    <Type Name="Product_Color">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Color" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_Color_Cart" Member="Carts" ThisKey="ID" OtherKey="ID_Product_Color" Type="Cart" />
      <Association Name="Product_Color_Bill_Detail" Member="Bill_Details" ThisKey="ID" OtherKey="ID_Product_Color" Type="Bill_Detail" />
      <Association Name="Colorr_Product_Color" Member="Colorr" ThisKey="ID_Color" OtherKey="ID" Type="Colorr" IsForeignKey="true" />
      <Association Name="Product_Product_Color" Member="Product" ThisKey="ID_Product" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product_Image" Member="Product_Images">
    <Type Name="Product_Image">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Product" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Product_Product_Image" Member="Product" ThisKey="ID_Product" OtherKey="ID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone_Number" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Customer_Bill" Member="Bills" ThisKey="ID" OtherKey="ID_Customer" Type="Bill" />
      <Association Name="Customer_Cart" Member="Carts" ThisKey="ID" OtherKey="ID_Customer" Type="Cart" />
      <Association Name="Customer_Favorites_list" Member="Favorites_lists" ThisKey="ID" OtherKey="ID_Customer" Type="Favorites_list" />
    </Type>
  </Table>
  <Table Name="dbo.Bill_Detail" Member="Bill_Details">
    <Type Name="Bill_Detail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_Bill" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_Product_Color" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="created_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updated_at" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comment" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="ratetime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="order_price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Bill_Bill_Detail" Member="Bill" ThisKey="ID_Bill" OtherKey="ID" Type="Bill" IsForeignKey="true" />
      <Association Name="Product_Color_Bill_Detail" Member="Product_Color" ThisKey="ID_Product_Color" OtherKey="ID" Type="Product_Color" IsForeignKey="true" />
    </Type>
  </Table>
</Database>