//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaptopNTT : DbContext
    {
        public LaptopNTT()
            : base("name=LaptopNTT")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<Bill_Detail> Bill_Detail { get; set; }
        public DbSet<Bill> Bills { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<Colorr> Colorrs { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Favorites_list> Favorites_list { get; set; }
        public DbSet<New_Image> New_Image { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Product_Color> Product_Color { get; set; }
        public DbSet<Product_Image> Product_Image { get; set; }
        public DbSet<Slide> Slides { get; set; }
    }
}
