//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Color
    {
        public Product_Color()
        {
            this.Bill_Detail = new HashSet<Bill_Detail>();
            this.Carts = new HashSet<Cart>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Color { get; set; }
        public Nullable<int> ID_Product { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual ICollection<Bill_Detail> Bill_Detail { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Colorr Colorr { get; set; }
        public virtual Product Product { get; set; }
    }
}
